./plate data/license_plates/est_095yhf_close.jpg 
./plate data/license_plates/f_an-684-fh_close.jpg 
./plate data/license_plates/gr_tkt-3442_close.jpg 
./plate data/license_plates/i_cz315ne_close.jpg 
./plate data/license_plates/i_ed485kc_close.jpg 
./plate data/license_plates/irl_132-ww-450_close.jpg 
./plate data/license_plates/md_chaw352_close.jpg 
./plate data/license_plates/n_dn96650_close.jpg 
./plate data/license_plates/pl_po3c008_close.jpg 
./plate data/license_plates/rus_am446739_close.jpg 
./plate data/license_plates/s_jmr297_close.jpg 
./plate data/license_plates/tr_34eu2170_close.jpg
